using Lesson1;
var myclass = new MyClass();
myclass.Fieald = "goodbye";
Console.WriteLine(myclass.Fieald);
myclass.Fieald = null;
Console.WriteLine(myclass.Fieald);
myclass.Fieald = "hello world";
Console.WriteLine(myclass.Fieald);
myclass.Fieald = "HAPPY NEW YEAR";
Console.WriteLine(myclass.Fieald);
